"""
Constrained function call generation.

This module contains the core of the project: a Generator that turns
a natural-language prompt into a structured function call.

The Generator combines several techniques to guarantee valid output:

- Function names are generated by walking a token trie, so only
  declared function names can be emitted.
- Numbers are generated by a small state machine that enforces valid
  numeric syntax.
- Booleans are generated by walking a token trie over ``true`` and
  ``false``.
- Strings are generated by matching tokens against a Cursor over the
  original user prompt, so strings come from the input rather than
  being hallucinated.
- Regex strings are generated by a finite state machine that enforces
  valid regex syntax.

The JSON skeleton (``{"name":"``, ``","parameters":{``, commas, and
closing braces) is injected directly as fixed tokens. Only the values
are chosen by the model, which is what makes the output 100% valid.
"""

import json

# from typing import TypedDict
from pydantic import BaseModel

import numpy as np
import numpy.typing as npt

from llm_sdk import Small_LLM_Model
from src.regex_rules import (
    ALLOWED_CHARS,
    RegexState,
    is_accepting,
    next_state,
)
from src.schema import FunctionDef, ParamType
from src.prompt import build_system_prompt
from src.cursor import Cursor


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

ParameterValue = str | float | bool

Parameters = dict[str, ParameterValue]


class FunctionCall(BaseModel):
    """A single function call prediction for one prompt."""

    prompt: str
    name: str
    parameters: Parameters


# ---------------------------------------------------------------------------
# Regex parameter detection
# ---------------------------------------------------------------------------

#: Words in a function description that hint at a regex parameter.
REGEX_DESC_WORDS = ('regex', 'regular expression', 'pattern')

#: Parameter names that hint at a regex parameter.
REGEX_PARAM_NAMES = frozenset({
    'regex', 'regexp', 'pattern', 'expr', 'expression',
    're', 'search', 'find', 'match',
})


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class UnsupportedParameterType(Exception):
    """Raised when a parameter has a type the generator cannot handle."""

    pass


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

class Generator:
    """
    Generates function calls from natural-language prompts.

    The Generator is initialized once with a model and a list of
    function definitions. It pre-computes several lookup tables
    (token tries, spans, FSM transitions) so that generating each
    function call is fast.

    Attributes are all private; callers only use ``build_function_call``.
    """

    def __init__(
        self,
        model: Small_LLM_Model,
        functions: list[FunctionDef],
    ) -> None:
        """
        Initialize the Generator.

        Args:
            model: The language model wrapper.
            functions: The function definitions to choose from.

        Raises:
            RuntimeError: If ``functions`` is empty or the model's
                vocabulary is missing or malformed.
        """
        if not functions:
            raise RuntimeError(
                "Generator needs at least one function definition; the "
                "name trie has nothing to choose between."
            )
        self._model: Small_LLM_Model = model
        self._functions: list[FunctionDef] = functions
        self._system_prompt: str = build_system_prompt(functions)

        # Pre-compute everything that does not depend on the prompt.
        self._encode_function_shapes(model, functions)
        self._encode_skeleton(model)
        vocab: dict[str, int] = self._load_vocabulary(model)
        self._classify_tokens(vocab)
        self._quote_token_id: int = self._find_quote_token(model, vocab)
        self._build_span_index(model)
        self._regex_transitions: dict[RegexState, dict[int, RegexState]] = (
            self._build_regex_transitions(vocab)
        )
        self._build_range_index(vocab)

    # -----------------------------------------------------------------------
    # Initialization helpers
    # -----------------------------------------------------------------------

    def _encode_function_shapes(
        self,
        model: Small_LLM_Model,
        functions: list[FunctionDef],
    ) -> None:
        """
        Pre-encode function names and parameter prefixes as token IDs.

        Args:
            model: The language model wrapper.
            functions: The function definitions.
        """
        self._name_to_tokens: dict[str, list[int]] = {}
        self._parameter_prefixes: dict[str, list[int]] = {}
        for func in functions:
            self._name_to_tokens[func.name] = (
                model.encode(func.name).squeeze(0).tolist()
            )
            for param_name in func.parameters:
                if param_name not in self._parameter_prefixes:
                    self._parameter_prefixes[param_name] = (
                        model.encode(
                            f'"{param_name}":'
                        ).squeeze(0).tolist()
                    )

    def _encode_skeleton(self, model: Small_LLM_Model) -> None:
        """
        Pre-encode the fixed JSON skeleton as token IDs.

        Args:
            model: The language model wrapper.
        """
        self._forced_tokens: list[int] = (
            model.encode('{"name":"').squeeze(0).tolist()
        )
        self._tokens_after_name: list[int] = (
            model.encode('","parameters":{').squeeze(0).tolist()
        )
        self._boolean_tokens: dict[str, list[int]] = {
            literal: model.encode(literal).squeeze(0).tolist()
            for literal in ("true", "false")
        }
        self._tokens_comma: list[int] = (
            model.encode(",").squeeze(0).tolist()
        )
        self._tokens_close: list[int] = (
            model.encode("}").squeeze(0).tolist()
        )

    @staticmethod
    def _load_vocabulary(model: Small_LLM_Model) -> dict[str, int]:
        """
        Load the model's vocabulary from its JSON file.

        Args:
            model: The language model wrapper.

        Returns:
            Mapping of token string to token ID.

        Raises:
            RuntimeError: If the vocabulary file is missing, malformed,
                or empty.
        """
        vocab_path: str = model.get_path_to_vocab_file()
        try:
            with open(vocab_path, "r", encoding="utf-8") as f:
                vocab: dict[str, int] = json.load(f)
        except FileNotFoundError:
            raise RuntimeError(
                f"Vocabulary file not found: {vocab_path}"
            )
        except json.JSONDecodeError as e:
            raise RuntimeError(
                f"Invalid vocabulary JSON in {vocab_path}: {e}"
            )
        if not vocab:
            raise RuntimeError(
                f"Vocabulary file is empty: {vocab_path}"
            )
        return vocab

    def _classify_tokens(self, vocab: dict[str, int]) -> None:
        """
        Classify tokens into useful groups (digits, dots, signs, etc.).

        Args:
            vocab: Mapping of token string to token ID.
        """
        self._digit_tokens: set[int] = set()
        self._dot_tokens: set[int] = set()
        self._minus_tokens: set[int] = set()
        self._terminator_tokens: set[int] = set()
        self._token_texts: dict[int, str] = {}
        for token_str, tok_id in vocab.items():
            stripped: str = token_str.strip()
            self._token_texts[tok_id] = token_str
            if stripped and all(c in "0123456789" for c in stripped):
                self._digit_tokens.add(tok_id)
            if stripped == ".":
                self._dot_tokens.add(tok_id)
            if stripped == "-":
                self._minus_tokens.add(tok_id)
            if stripped in (",", "}"):
                self._terminator_tokens.add(tok_id)

    @staticmethod
    def _find_quote_token(
        model: Small_LLM_Model, vocab: dict[str, int]
    ) -> int:
        """
        Find the token ID for a standalone double-quote.

        Args:
            model: The language model wrapper.
            vocab: Mapping of token string to token ID.

        Returns:
            The token ID for ``"``.

        Raises:
            RuntimeError: If the vocabulary has no standalone quote.
        """
        quote_id: int | None = vocab.get('"')
        if quote_id is None:
            raise RuntimeError(
                f"Vocabulary at {model.get_path_to_vocab_file()} has no "
                "standalone '\"' token; JSON strings cannot be delimited."
            )
        return quote_id

    @staticmethod
    def _is_emittable_text(text: str) -> bool:
        """
        Check if a token's text can appear in a JSON string.

        A token is emittable if it is non-empty, consists only of
        printable ASCII, and contains no double-quote (which would
        break the string).

        Args:
            text: The token text.

        Returns:
            True if the token can be emitted inside a JSON string.
        """
        return bool(text) and all(
            0x20 <= ord(c) <= 0x7E and c != '"' for c in text
        )

    def _build_span_index(self, model: Small_LLM_Model) -> None:
        """
        Index tokens by their first character for fast lookup.

        Args:
            model: The language model wrapper.
        """
        decoded_by_id = (
            (tok_id, str(model.decode([tok_id])))
            for tok_id in self._token_texts
            if tok_id != self._quote_token_id
        )
        self._decoded_texts: dict[int, str] = {
            tok_id: decoded
            for tok_id, decoded in decoded_by_id
            if self._is_emittable_text(decoded)
        }
        self._tokens_by_first_char: dict[str, list[tuple[int, str]]] = {}
        seen_decoded: set[str] = set()
        for tok_id, decoded in self._decoded_texts.items():
            if decoded in seen_decoded:
                continue
            seen_decoded.add(decoded)
            self._tokens_by_first_char.setdefault(
                decoded[0], []
            ).append((tok_id, decoded))

    # -----------------------------------------------------------------------
    # Regex FSM helpers
    # -----------------------------------------------------------------------

    @staticmethod
    def _state_after_token(
        start_state: RegexState, token_str: str
    ) -> RegexState | None:
        """
        Compute the FSM state after consuming an entire token.

        Walks the FSM character by character. Returns ``None`` if any
        character is not allowed in its state, or if a range endpoint
        is smaller than its start (e.g. ``[z-a]``).

        Args:
            start_state: The FSM state before the token.
            token_str: The token's text.

        Returns:
            The FSM state after the token, or ``None`` if invalid.
        """
        state: RegexState = start_state
        run_len = 0
        range_start: str | None = None
        prev_ch: str | None = None
        for ch in token_str:
            if ch not in ALLOWED_CHARS[state]:
                return None
            if (state == RegexState.CLASS_RANGE
                    and range_start is not None
                    and ord(ch) < ord(range_start)):
                return None
            if state == RegexState.CLASS_BODY and ch == '-':
                range_start = prev_ch
            prev_ch = ch
            state = next_state(state, ch, run_len)
            grew = state in (
                RegexState.LITERAL_BODY,
                RegexState.CLASS_BODY,
            )
            run_len = run_len + 1 if grew else 0
        return state

    def _build_regex_transitions(
        self, vocab: dict[str, int]
    ) -> dict[RegexState, dict[int, RegexState]]:
        """
        Pre-compute FSM transitions for every token and state.

        Args:
            vocab: Mapping of token string to token ID.

        Returns:
            A dict mapping each state to a dict of token ID → next state.
        """
        transitions: dict[RegexState, dict[int, RegexState]] = {
            s: {} for s in RegexState
        }
        for token_str, tok_id in vocab.items():
            if not self._is_emittable_text(token_str):
                continue
            for start_state in RegexState:
                reached = self._state_after_token(start_state, token_str)
                if reached is not None:
                    transitions[start_state][tok_id] = reached
        return transitions

    def _build_range_index(self, vocab: dict[str, int]) -> None:
        """
        Index tokens that start with a dash (e.g. ``-a``) for ranges.

        Args:
            vocab: Mapping of token string to token ID.
        """
        self._range_opening_tokens: dict[int, str] = {
            tok_id: token_str[1]
            for token_str, tok_id in vocab.items()
            if len(token_str) > 1 and token_str[0] == '-'
        }

    # -----------------------------------------------------------------------
    # Main entry point
    # -----------------------------------------------------------------------

    def build_function_call(self, prompt_text: str) -> FunctionCall:
        """
        Build a function call from a natural-language prompt.

        Args:
            prompt_text: The user's request.

        Returns:
            A ``FunctionCall`` dict with ``prompt``, ``name``, and
            ``parameters``.

        Raises:
            RuntimeError: If the generated name matches no function.
        """
        full_prompt: str = (
            self._system_prompt
            + "\n\nUser request: "
            + prompt_text
            + "\nResponse: "
        )
        inputs_ids: list[int] = self._model.encode(
            full_prompt
        ).squeeze(0).tolist()
        for tok in self._forced_tokens:
            inputs_ids.append(tok)

        chosen_name: str = self._generate_function_name(inputs_ids)
        try:
            chosen_func: FunctionDef = next(
                f for f in self._functions if f.name == chosen_name
            )
        except StopIteration:
            raise RuntimeError(
                f"generated name {chosen_name!r} matches no declared "
                "function"
            )
        # Use the declared spelling rather than the decoded one.
        chosen_name = chosen_func.name

        parameters: Parameters = self._generate_parameters(
            inputs_ids, chosen_func, prompt_text
        )
        return FunctionCall(
            prompt=prompt_text,
            name=chosen_name,
            parameters=parameters,
        )

    # -----------------------------------------------------------------------
    # Token selection
    # -----------------------------------------------------------------------

    def _preferred_token(
        self, input_ids: list[int], allowed: set[int]
    ) -> int:
        """
        Pick the highest-scoring token among the allowed ones.

        Args:
            input_ids: The current input token IDs.
            allowed: The set of allowed token IDs.

        Returns:
            The token ID with the highest logit among the allowed set.
        """
        if len(allowed) == 1:
            return next(iter(allowed))
        logits: list[float] = self._model.get_logits_from_input_ids(
            input_ids
        )
        logits_array: npt.NDArray[np.float64] = np.array(logits)
        mask: npt.NDArray[np.bool_] = np.full(
            len(logits_array), False
        )
        for tok_id in allowed:
            mask[tok_id] = True
        logits_array[~mask] = -np.inf
        return int(np.argmax(logits_array))

    # -----------------------------------------------------------------------
    # Function name generation (trie walk)
    # -----------------------------------------------------------------------

    def _generate_function_name(self, input_ids: list[int]) -> str:
        """
        Generate a function name by walking the name trie.

        At each step, only tokens that extend at least one declared
        function name are allowed. Stops when a complete name is matched.

        Args:
            input_ids: The current input token IDs (mutated in place).

        Returns:
            The decoded function name.

        Raises:
            RuntimeError: If no function name matches the emitted tokens.
        """
        generated_so_far: list[int] = []
        while True:
            candidates = [
                name
                for name, tokens in self._name_to_tokens.items()
                if tokens[: len(generated_so_far)] == generated_so_far
            ]
            is_complete: bool = any(
                self._name_to_tokens[name] == generated_so_far
                for name in candidates
            )
            if is_complete:
                break
            if not candidates:
                raise RuntimeError(
                    "no function name matches the tokens emitted so far"
                )
            allowed: set[int] = set()
            for name in candidates:
                tokens: list[int] = self._name_to_tokens[name]
                if len(generated_so_far) < len(tokens):
                    allowed.add(tokens[len(generated_so_far)])
            next_token_id: int = self._preferred_token(input_ids, allowed)
            generated_so_far.append(next_token_id)
            input_ids.append(next_token_id)
        return str(self._model.decode(generated_so_far))

    # -----------------------------------------------------------------------
    # Boolean generation (trie walk)
    # -----------------------------------------------------------------------

    def _generate_boolean(self, input_ids: list[int]) -> bool:
        """
        Generate a boolean by walking the ``true``/``false`` trie.

        Args:
            input_ids: The current input token IDs (mutated in place).

        Returns:
            The generated boolean value.
        """
        candidates = self._boolean_tokens
        emitted: list[int] = []
        while True:
            alive = [
                literal
                for literal, tokens in candidates.items()
                if tokens[: len(emitted)] == emitted
            ]
            complete = [
                literal for literal in alive
                if candidates[literal] == emitted
            ]
            if complete and len(alive) == 1:
                return complete[0] == "true"
            allowed = {
                candidates[literal][len(emitted)]
                for literal in alive
                if len(candidates[literal]) > len(emitted)
            }
            if not allowed:
                return bool(complete) and complete[0] == "true"
            next_token_id = self._preferred_token(input_ids, allowed)
            emitted.append(next_token_id)
            input_ids.append(next_token_id)

    # -----------------------------------------------------------------------
    # Number generation (state machine)
    # -----------------------------------------------------------------------

    def _allowed_number_tokens(
        self,
        emitted: int,
        has_sign: bool,
        has_dot: bool,
        digits_after_dot: int,
    ) -> set[int]:
        """
        Compute the allowed tokens for the current number state.

        Args:
            emitted: Number of tokens emitted so far.
            has_sign: Whether a minus sign was already emitted.
            has_dot: Whether a decimal point was already emitted.
            digits_after_dot: Number of digits after the decimal point.

        Returns:
            The set of allowed token IDs.
        """
        if emitted == 0:
            return set(self._digit_tokens) | set(self._minus_tokens)
        if has_sign and emitted == 1:
            return set(self._digit_tokens)
        if has_dot and digits_after_dot == 0:
            return set(self._digit_tokens)
        allowed = set(self._digit_tokens) | set(self._terminator_tokens)
        if not has_dot:
            allowed |= set(self._dot_tokens)
        return allowed

    def _generate_number(self, input_ids: list[int]) -> float:
        """
        Generate a number using a small state machine.

        The state machine enforces valid numeric syntax: optional minus
        sign, digits, optional decimal point, more digits. A hard cap
        on the number of tokens prevents infinite loops when the model
        never picks a terminator.

        Args:
            input_ids: The current input token IDs (mutated in place).

        Returns:
            The generated number as a float.
        """
        generated_digits: list[int] = []
        has_sign: bool = False
        has_dot: bool = False
        digits_after_dot: int = 0
        # A cap is essential, not defensive. Without one the loop
        # depends entirely on the model choosing a terminator, and a
        # request with no number in it ("Add the numbers together")
        # never does: the context grows without bound, each iteration
        # costing another forward pass over it.
        MAX_NUMBER_TOKENS = 24
        for _ in range(MAX_NUMBER_TOKENS):
            allowed: set[int] = self._allowed_number_tokens(
                len(generated_digits), has_sign, has_dot, digits_after_dot
            )
            next_token_id: int = self._preferred_token(
                input_ids, allowed
            )
            if next_token_id in self._terminator_tokens:
                break
            generated_digits.append(next_token_id)
            input_ids.append(next_token_id)
            if next_token_id in self._minus_tokens:
                has_sign = True
            elif next_token_id in self._dot_tokens:
                has_dot = True
            elif has_dot:
                digits_after_dot += 1
        return float(self._model.decode(generated_digits))

    # -----------------------------------------------------------------------
    # Regex string generation (FSM)
    # -----------------------------------------------------------------------

    def _mask_range_endpoint(
        self,
        masked: npt.NDArray[np.float64],
        allowed_map: dict[int, RegexState],
        text: str,
    ) -> None:
        """
        Mask range endpoints that are smaller than the range start.

        Args:
            masked: The logits array (mutated in place).
            allowed_map: The allowed token → state map.
            text: The text generated so far.
        """
        if len(text) < 2:
            return
        start = text[-2]
        for tok_id in allowed_map:
            if ord(self._token_texts[tok_id][0]) < ord(start):
                masked[tok_id] = -np.inf

    def _mask_range_opening(
        self,
        masked: npt.NDArray[np.float64],
        allowed_map: dict[int, RegexState],
        text: str,
    ) -> None:
        """
        Mask range openings whose endpoint is smaller than the start.

        Args:
            masked: The logits array (mutated in place).
            allowed_map: The allowed token → state map.
            text: The text generated so far.
        """
        if not text:
            return
        start = text[-1]
        for tok_id, endpoint in self._range_opening_tokens.items():
            if tok_id in allowed_map and ord(endpoint) < ord(start):
                masked[tok_id] = -np.inf

    def _mask_bad_ranges(
        self,
        masked: npt.NDArray[np.float64],
        allowed_map: dict[int, RegexState],
        fsm_state: RegexState,
        text: str,
    ) -> None:
        """
        Apply range-specific masks based on the current FSM state.

        Args:
            masked: The logits array (mutated in place).
            allowed_map: The allowed token → state map.
            fsm_state: The current FSM state.
            text: The text generated so far.
        """
        if fsm_state == RegexState.CLASS_RANGE:
            self._mask_range_endpoint(masked, allowed_map, text)
        elif fsm_state == RegexState.CLASS_BODY:
            self._mask_range_opening(masked, allowed_map, text)

    def _generate_regex_string(self, input_ids: list[int]) -> str:
        """
        Generate a regex string using the regex FSM.

        Args:
            input_ids: The current input token IDs (mutated in place).

        Returns:
            The generated regex string.
        """
        input_ids.append(self._quote_token_id)
        generated: list[int] = []
        text = ""
        fsm_state: RegexState = RegexState.START
        MAX_STRING_TOKENS = 16
        for _ in range(MAX_STRING_TOKENS):
            allowed_map = self._regex_transitions[fsm_state]
            logits: list[float] = (
                self._model.get_logits_from_input_ids(input_ids)
            )
            logits_array: npt.NDArray[np.float64] = np.array(logits)
            masked: npt.NDArray[np.float64] = np.full(
                len(logits_array), -np.inf
            )
            if is_accepting(fsm_state):
                masked[self._quote_token_id] = (
                    logits_array[self._quote_token_id]
                )
            for tok_id in allowed_map:
                masked[tok_id] = logits_array[tok_id]
            self._mask_bad_ranges(masked, allowed_map, fsm_state, text)
            if not np.any(np.isfinite(masked)):
                input_ids.append(self._quote_token_id)
                return str(self._model.decode(generated))
            next_token_id: int = int(np.argmax(masked))
            input_ids.append(next_token_id)
            if next_token_id == self._quote_token_id:
                return str(self._model.decode(generated))
            fsm_state = allowed_map[next_token_id]
            generated.append(next_token_id)
            text += self._token_texts[next_token_id]
        input_ids.append(self._quote_token_id)
        return str(self._model.decode(generated))

    # -----------------------------------------------------------------------
    # Substring generation (cursor over user prompt)
    # -----------------------------------------------------------------------

    def _candidate_tokens(
        self, tracker: Cursor
    ) -> list[tuple[int, str]]:
        """
        Get candidate tokens whose first char matches a cursor position.

        Args:
            tracker: The live cursor.

        Returns:
            A list of ``(token_id, token_text)`` candidates.
        """
        next_chars = tracker.next_chars()
        out: list[tuple[int, str]] = []
        for ch in next_chars:
            out.extend(self._tokens_by_first_char.get(ch, []))
        return out

    def _span_mask(
        self,
        tracker: Cursor,
        logits_array: npt.NDArray[np.float64],
    ) -> npt.NDArray[np.float64]:
        """
        Build the mask admitting only tokens the cursor can absorb.

        Args:
            tracker: The live cursor.
            logits_array: This step's scores.

        Returns:
            The mask. Starts fully forbidden and adds legality back, so
            a gap anywhere truncates the value rather than corrupting
            it. Whether anything survived is read off the mask itself by
            the caller, which has to test it regardless.
        """
        masked: npt.NDArray[np.float64] = np.full(
            len(logits_array), -np.inf
        )
        for tok_id, chars in self._candidate_tokens(tracker):
            if tracker.accepts(chars):
                masked[tok_id] = logits_array[tok_id]
        return masked

    @staticmethod
    def _is_quote_content(
        tracker: Cursor, quotes_emitted: int
    ) -> bool:
        """
        Check whether a double-quote is content or a string terminator.

        Args:
            tracker: The live cursor.
            quotes_emitted: Number of quotes emitted so far.

        Returns:
            True if the quote should be treated as content.
        """
        if not tracker.accepts('"'):
            return False
        if quotes_emitted % 2 == 1:
            return True
        return any(
            pos < len(tracker.source)
            and tracker.source[pos] == '"'
            and '"' in tracker.source[pos + 1:]
            for pos in tracker.positions
        )

    def _accept_span_token(
        self, tracker: Cursor, tok_id: int
    ) -> None:
        """
        Advance the cursor by the text of a token.

        Args:
            tracker: The live cursor.
            tok_id: The token ID to accept.
        """
        if tok_id == self._quote_token_id:
            tracker.advance('"')
            return
        tracker.advance(self._decoded_texts.get(
            tok_id, self._model.decode([tok_id])
        ))

    def _generate_substring(
        self,
        input_ids: list[int],
        user_prompt: str,
    ) -> str:
        """
        Generate a substring by matching tokens against the user prompt.

        Args:
            input_ids: The current input token IDs (mutated in place).
            user_prompt: The original user prompt to match against.

        Returns:
            The generated substring.
        """
        input_ids.append(self._quote_token_id)
        tracker: Cursor = Cursor(user_prompt)
        generated: list[int] = []
        quotes_emitted: int = 0
        MAX_STRING_TOKENS: int = 64
        for _ in range(MAX_STRING_TOKENS):
            logits: list[float] = (
                self._model.get_logits_from_input_ids(input_ids)
            )
            logits_array: npt.NDArray[np.float64] = np.array(logits)
            masked = self._span_mask(tracker, logits_array)
            allow_close: bool = bool(generated)
            quote_is_content: bool = self._is_quote_content(
                tracker, quotes_emitted
            )
            if allow_close or quote_is_content:
                masked[self._quote_token_id] = (
                    logits_array[self._quote_token_id]
                )
            if not np.any(np.isfinite(masked)):
                input_ids.append(self._quote_token_id)
                return str(self._model.decode(generated))
            next_token_id = int(np.argmax(masked))
            input_ids.append(next_token_id)
            is_quote = next_token_id == self._quote_token_id
            if is_quote and not quote_is_content:
                return str(self._model.decode(generated))
            quotes_emitted += int(is_quote)
            self._accept_span_token(tracker, next_token_id)
            generated.append(next_token_id)
        input_ids.append(self._quote_token_id)
        return str(self._model.decode(generated))

    # -----------------------------------------------------------------------
    # Value dispatch
    # -----------------------------------------------------------------------

    def _is_regex_parameter(
        self, param_name: str, func: FunctionDef
    ) -> bool:
        """
        Check whether a parameter should be treated as a regex.

        Args:
            param_name: The parameter name.
            func: The function definition.

        Returns:
            True if the parameter is a regex parameter.
        """
        description = func.description.lower()
        if not any(word in description for word in REGEX_DESC_WORDS):
            return False
        return param_name.lower() in REGEX_PARAM_NAMES

    def _generate_value(
        self,
        input_ids: list[int],
        param_name: str,
        func: FunctionDef,
        user_prompt: str,
    ) -> ParameterValue:
        """
        Generate a parameter value based on its declared type.

        Args:
            input_ids: The current input token IDs (mutated in place).
            param_name: The parameter name.
            func: The function definition.
            user_prompt: The original user prompt.

        Returns:
            The generated value.

        Raises:
            UnsupportedParameterType: If the type is unsupported.
        """
        param_type: ParamType = func.parameters[param_name].type
        if param_type.value == "number":
            return self._generate_number(input_ids)
        if param_type.value == "integer":
            return int(self._generate_number(input_ids))
        if param_type.value == "boolean":
            return self._generate_boolean(input_ids)
        if param_type.value == "string":
            if self._is_regex_parameter(param_name, func):
                return self._generate_regex_string(input_ids)
            return self._generate_substring(
                input_ids, user_prompt
            ).strip()
        declared: str = func.parameters[param_name].declared_type
        raise UnsupportedParameterType(
            f"parameter {param_name!r} has unsupported type {declared!r}"
        )

    # -----------------------------------------------------------------------
    # Parameters
    # -----------------------------------------------------------------------

    def _generate_parameters(
        self,
        input_ids: list[int],
        func: FunctionDef,
        user_prompt: str,
    ) -> Parameters:
        """
        Generate all parameters for a function call.

        Args:
            input_ids: The current input token IDs (mutated in place).
            func: The function definition.
            user_prompt: The original user prompt.

        Returns:
            A dict mapping parameter names to their generated values.
        """
        parameters: Parameters = {}
        input_ids.extend(self._tokens_after_name)
        param_names: list[str] = list(func.parameters.keys())
        for i, param_name in enumerate(param_names):
            input_ids.extend(self._parameter_prefixes[param_name])
            parameters[param_name] = self._generate_value(
                input_ids, param_name, func, user_prompt
            )
            if i < len(param_names) - 1:
                input_ids.extend(self._tokens_comma)
        input_ids.extend(self._tokens_close)
        return parameters
